### ISSUE TITLE
Cave Tiers

### ISSUE THREAD

**Issue by nevir** [turbulenz/boundless.worlds#12]
I'd like to propose "cave tiers", where certain cave configurations are tied to world difficulty.

Our current worlds are kind of all over the place in terms of difficult to navigate caves.  I think having a cave noise function per difficulty might be good enough.  Maybe aligned with world tiers?

---

There are several factors that (when tuned) seem to make caves more approachable to beginners:

**Verticality:** Caves that are lightly sloped are very approachable; beginners can explore a cave without having to build stairs up/down.

**Narrowness:** Caves that are relatively narrow (tubelike) can be better for beginners, because their torch's light can reach the sides of the cave they're in.  (Alternative are very wide caves, and blackness in many directions for the player)

**Surface Drop:** Whenever a cave breaks the surface, beginners are more likely to follow it (as opposed to digging in random directions).  However, there shouldn't be huge holes in the ground, either (difficult to navigate surface).

**Interconnectedness:** Caves that are too interconnected are easy to get lost in; caves that are too short are generally boring.

---

I think this can be boiled down into a few cave noise functions, and configurations of them for each world:

**Beginner Caves:** Lightly sloped without any large drops, narrow/tubelike, and decently interconnected.  _I think the [CavesStandard](https://github.com/turbulenz/boundless.worlds/blob/master/config/noise3d/CavesStandard.json) function is pretty close to this already; it just could use more gentle slopes._

**Intermediate Caves**: A mix of beginner caves (maybe with steeper slopes), and some more challenging features like: ravines (Minecraft style?), open caverns, more interconnections, etc.

**Advanced Caves**: Steeply sloped caves, large drops, swiss cheese caves, huge surface openings, no surface openings, etc.

---

Some thoughts on difficulty:

**Beginner Worlds:** A player should be able to find caves in any biome, and should be able to navigate them without much digging, or a grappling hook.

**Intermediate Worlds:** A player should be able to find caves in any biome, but may require some digging/building/grappling to navigate some areas.

Advanced Worlds: Most biomes have difficult to traverse caves. Some biomes' caves are hidden; require digging to find them.

**Comment by DamTerrion** [comment]
Love this idea. It seems so deliberate :)
