### ISSUE TITLE
River and water system 1 heightmaps

### ISSUE THREAD

**Issue by willcrutchley** [turbulenz/boundless.worlds#19]
The river and water system height maps seem to be broken (they are completely blank when visualised). However it may just be that these do not work on the version of worldbuilder available on live 🤔 Sorry if that is the case!

**Comment by nevir** [comment]
Could you save the config you're working with?  I'm unable to reproduce it for either of those nodes when previewing them directly, at least

(with the latest release, and testing builds)

**Comment by willcrutchley** [comment]
If, for example, you view the heightmap of the ice walkway biome (in config/biomes/release/tier 7/) the heightmap I see is entirely flat. I see the same thing when previewing the 2 nodes I mentioned directly too...
![20180402171713_1](https://user-images.githubusercontent.com/18472261/38204192-c3ee37ac-3699-11e8-8771-60b28ceee78f.jpg)
![20180402171731_1](https://user-images.githubusercontent.com/18472261/38204193-c4069644-3699-11e8-8d11-ae1f439ed1eb.jpg)

**Comment by willcrutchley** [comment]
unless of course, I have misunderstood 😜

**Comment by nevir** [comment]
Hmmm

![image](https://user-images.githubusercontent.com/41373/38205235-abfcf1cc-365a-11e8-85b2-9523c190a635.png)

**Comment by nevir** [comment]
I'm curious: how are you pulling down this repo to work with it? I'm wondering if you're missing some of the referenced node definitions, or if they're in locations where the WB doesn't expect

**Comment by nevir** [comment]
FWIW, the way I've been devving against the repo is to check it out, and then symlink the game's copy to point to my checked out repo.  The game then drops a bunch of the baked in configs whenever you start the WB, but beyond that it works pretty well

**Comment by willcrutchley** [comment]
I just cloned the repo and chucked in this config folder in place of the original one, so that could be causing issues

**Comment by willcrutchley** [comment]
I'll try your method, and see what happens 👍

**Comment by willcrutchley** [comment]
Still not working for me. Did you create a hard link? or a soft link? Interestingly worldbuilder still shows all the inbuilt configs, even though they no longer exist at all. It even shows them in the biomes directory despite them not being there...

**Comment by nevir** [comment]
> Still not working for me. Did you create a hard link? or a soft link? 

Soft (darwin)

> Interestingly worldbuilder still shows all the inbuilt configs, even though they no longer exist at all. It even shows them in the biomes directory despite them not being there...

Yeah, it will splat out all inbuilt configs on launch (until they pull from this repo w/ the next release).  When the repo gets ahead, it's often helpful to `git clean -fdx` (but make sure you don't have any pending changes of your own!) after booting WB

**Comment by nevir** [comment]
One thing to try: 

1. walk into dependencies of the nodes you're trying to play with
2. Make an edit (drag some nodes around, anything)
3. Save it.

Some of the configs in the repo are for the v16 schema, which isn't available to us.  Saving it will migrate to the WB's currently known schema.

I was having some issues with `Offset`, and a few others, not emitting anything useful until I did that.  (But the water system & that biome were fine w/o doing this, for me)

**Comment by willcrutchley** [comment]
Hmm, still not functioning correctly. Out of interest, what do you see when you preview the water system heightmap directly?

**Comment by nevir** [comment]
![image](https://user-images.githubusercontent.com/41373/38322164-7ec8d3c0-37ee-11e8-9ddc-fcb402f62f52.png)

**Comment by willcrutchley** [comment]
Looks like I have fixed it, at least it now displays a heightmap other than flat (although it doesn't look like your's)
For reference, you were correct about needing to resave the configs in the old format, I just didn't try it with the rivers config which water system is dependent on 🙄

**Comment by nevir** [comment]
Aha! Maybe we should set up a branch with v15 configs for us to play on
until the latest version of the WB lands

Though, weirdly, I'm able to preview stuff with v16 rivers too.  I think my
mental model of what's going on has some holes in it

**Comment by willcrutchley** [comment]
OK, I'm now getting the same as you for water system, idk how it's working, but it is :joy:
